# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yc5qM-c-CKiHi7CugXkrXQXr1g-MPP6b
"""

from janome.tokenizer import Tokenizer
import json
from flask import Flask, request, jsonify, render_template

app = Flask(__name__)
tokenizer = Tokenizer()

with open("ero_score_dict.json", encoding="utf-8") as f:
    score_dict = json.load(f)

def tokenize(text):
    return [token.surface for token in tokenizer.tokenize(text)]

def classify_ero(text, score_dict):
    words = tokenize(text)
    return sum(score_dict.get(w, 0) for w in words)

@app.route('/')
def index():
    return render_template("index.html")

@app.route('/score', methods=['POST'])
def score():
    data = request.get_json()
    text = data.get("text", "")
    score = classify_ero(text, score_dict)
    return jsonify({'score': score})

if __name__ == '__main__':
    app.run(debug=True)

